name: Dev CI Pipeline

on:
  push:
    branches:
      - dev

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Run ESLint
        run: yarn lint

  test:
    name: Run Unit Tests and Collect Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Run Jest tests with coverage
        run: yarn test --coverage
      - name: Upload coverage to CodeCov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  sonarcloud:
    name: SonarCloud Code Analysis
    runs-on: ubuntu-latest
    if: ${{ needs.test.result == 'success' }} # Run only if the test job is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full depth is recommended for accurate SonarCloud analysis

      - name: Install dependencies
        run: yarn install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  auto_merge:
    name: Auto-Merge Dev into Main if All Pass
    runs-on: ubuntu-latest
    needs: [lint, test, sonarcloud]
    steps:
      - name: Checkout the dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Merge dev into main
        run: |
          git checkout main
          git merge dev
      - name: Push merge to main
        run: |
          git push origin main
