name: Main Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Generate documentation
        run: yarn run docs

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs


  deploy:
    name: Build and Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Build the project
        run: yarn build
      - name: Deploy to Vercel
        run: yarn vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  database:
    name: Apply Migrations on Neon PostgresSQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Apply migrations
        run: yarn typeorm migration:run
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
